Repository jenkinsci/json-path-api-plugin, pull requests merged in 2023-12, with the labels that each got.

#1 Remove master reference
  .github/workflows/jenkins-security-scan.yml
Labels: skip-changelog, chore

#3 Fix resource filtering
  pom.xml
Labels: chore

#4 Upgrade `json-smart` to latest
  pom.xml
Labels: dependencies, java

#7 License adapt for API plugin
  LICENSE.md
  pom.xml
Labels: documentation
